### ISSUE TITLE
Snakemake execution fails

### ISSUE THREAD

**Issue by benedict909** [friendsofstrandseq/mosaicatcher-pipeline#1]
Hello,

Benedict here, PhD student working with Ashley in Berlin 🙂 

I'm trying to run the pipeline using the Singularity image. 

I have tried my best to provide the correct input/apply the relevant changes to the config file, but when I execute the Snakemake the job finishes (without error) after ~20 seconds.

Here is the end of my log file (which to me suggests the input data is found?): 

`Detected 1 samples:
  D2RFbO2_20171122:     192 cells        192 selected cells`

Any idea why this might be?

Thanks for your help!
Benedict

**Comment by weber8thomas** [comment]
Hi Benedict ! 

I'm Thomas, new postdoc in the group of Jan, working on MosaiCatcher improvements.

> Detected 1 samples: D2RFbO2_20171122: 192 cells 192 selected cells

Okay, looks like the folder structure (sample/all ; sample/selected) is respected. 

Could you paste here the complete log please ? 

Would it be possible to have the snakemake execution command and your config file additionally ?

Thanks,

Thomas

**Comment by benedict909** [comment]
Hi Thomas!

Thanks for your quick response! 🙂 

Here is my complete log, the "no change" bit is just from me activating a conda enviornment that has snakemake and singularity installed. 

`no change     /data/gpfs-1/users/bmontei_m/work/miniconda/condabin/conda
no change     /data/gpfs-1/users/bmontei_m/work/miniconda/bin/conda
no change     /data/gpfs-1/users/bmontei_m/work/miniconda/bin/conda-env
no change     /data/gpfs-1/users/bmontei_m/work/miniconda/bin/activate
no change     /data/gpfs-1/users/bmontei_m/work/miniconda/bin/deactivate
no change     /data/gpfs-1/users/bmontei_m/work/miniconda/etc/profile.d/conda.sh
no change     /data/gpfs-1/users/bmontei_m/work/miniconda/etc/fish/conf.d/conda.fish
no change     /data/gpfs-1/users/bmontei_m/work/miniconda/shell/condabin/Conda.psm1
no change     /data/gpfs-1/users/bmontei_m/work/miniconda/shell/condabin/conda-hook.ps1
no change     /data/gpfs-1/users/bmontei_m/work/miniconda/lib/python3.10/site-packages/xontrib/conda.xsh
no change     /data/gpfs-1/users/bmontei_m/work/miniconda/etc/profile.d/conda.csh
no change     /data/gpfs-1/users/bmontei_m/.bashrc
No action taken.
Config file Snake.config.json is extended by additional config specified via the command line.
Unlocking working directory.
Detected 1 samples:
  D2RFbO2_20171122:     192 cells        192 selected cells`


Snakemake execution command: 

`REF="/fast/groups/ag_sanders/work/data/reference/genomes/GCA_000001405.15_GRCh38_no_alt_analysis_set.fna.gz"
R_REF="/data/gpfs1/users/bmontei_m/work/miniconda/envs/pipeline/lib/R/library/BSgenome.Hsapiens.UCSC.hg38/extdata/single_sequences.2bit"

snakemake \
    -j 32 \
    --configfile Snake.config-singularity.json \
    --use-singularity \
    --singularity-args \
       "-B ${REF}:/reference.fa:ro \
        -B ${REF}.fai:/reference.fa.fai:ro \
        -B ${R_REF}:/usr/local/lib/R/site-library/BSgenome.Hsapiens.UCSC.hg38/extdata/single_sequences.2bit:ro" \
    --latency-wait 60 \
    --printshellcmd \
    --unlock`

My Snake.config-singularity.json file:

`{
    "chromosomes"   : ["chr1","chr2","chr3","chr4","chr5","chr6","chr7","chr8","chr9","chr10","chr11","chr12","chr13","chr14","chr15","chr16","chr17","chr18","chr19","chr20","chr21","chr22","chrX"],

    "snv_sites_to_genotype" : "//fast/groups/ag_sanders/work/data/reference/snv_sites_to_genotype/ALL.chr1-22plusX_GRCh38_sites.20170504.renamedCHR.vcf.gz",

    "reference"     : "//fast/groups/ag_sanders/work/data/reference/genomes/GCA_000001405.15_GRCh38_no_alt_analysis_set.fna.gz",
    "mosaicatcher"  : "mosaic",
    "plot_script"   : "/mosaicatcher/R/qc.R",
    "sv_plot_script": "/mosaicatcher/R/chrom.R",
    "norm_script"   : "/mosaicatcher/R/norm.R",
    "samtools"      : "samtools",
    "bcftools"      : "bcftools",

    "variable_bins" : {
        "50000"     : "utils/variable_bins.GRCh38.50kb.bed",
        "100000"    : "utils/variable_bins.GRCh38.100kb.bed"
    },
    "R_reference"   : "BSgenome.Hsapiens.UCSC.hg38",

    "bp_density"    : {
        "few"       : 0.2,
        "medium"    : 0.4,
        "many"      : 0.6
    },

    "paired_end"    : true,

    "ground_truth_clonal" : { "RPE-BM510" : ""},
    "ground_truth_single_cell" : { "RPE-BM510" : ""},


    "simulation_min_vaf" : 0.01,
    "simulation_max_vaf" : 1.0,
    "simulation_neg_binom_p" : {
        "50000" : 0.4,
        "100000" : 0.3,
        "500000" : 0.1
    },
    "simulation_min_reads_per_library" :  500000,
    "simulation_max_reads_per_library" : 1000000,
    "simulation_window_sizes" : [50000, 100000],
    "simulation_cell_count" : 100,
    "simulation_alpha" : 0.02,

    "genome_size" : 3e9

}`

Sorry if there is a basic error in there somewhere, I'm not very experienced with snakemake!

Thanks,
Benedict

Edit: sorry for messy formatting this is the best I can manage

**Comment by weber8thomas** [comment]
Sorry for the naive question but did you keep the `\` antislash escape characters when running the snakemake command to separate each argument ?
I'm asking as the log seems to tell that snakemake do not have taken into account the change of JSON config file : 

> Config file **Snake.config.json** is extended by additional config specified via the command line.

What versions of snakemake and singularity are you using ? 

How did you install snakemake ?

Thanks for the answers :)

**Comment by benedict909** [comment]
Yes sorry github didn't like my formatting, here is the snakemake command I'm running: 

```
snakemake \
    -j 32 \
    --configfile Snake.config-singularity.json \
    --use-singularity \
    --singularity-args \
       "-B ${REF}:/reference.fa:ro \
        -B ${REF}.fai:/reference.fa.fai:ro \
        -B ${R_REF}:/usr/local/lib/R/site-library/BSgenome.Hsapiens.UCSC.hg38/extdata/single_sequences.2bit:ro" \
    --latency-wait 60 \
    --printshellcmd \
    --unlock
```

I added `--unlock` as I was getting an error otherwise. 

I'm using snakemake 7.3.8 and singularity 3.8.7, and I installed snakemake via `conda install -c bioconda snakemake`

**Comment by weber8thomas** [comment]
Ok thanks, just to be sure that it's not on snakemake version, could you try on a separate environment with snakemake 5.10 please ? 

Additionally, could you paste the error without the `--unlock` option ?

**Comment by benedict909** [comment]
Ok removing `--unlock` seems to work better (not sure why I needed it yesterday, thanks for the suggestion!), although unfortunately the execution still fails.

My log is now quite long so I'll share it via [dropbox](https://www.dropbox.com/s/qmj5gi6uxibn73f/20220426_scTRIP_snakemake5.10.txt?dl=0).

It seems to me the main error is this: `/data/gpfs-1/users/bmontei_m/work/miniconda/envs/pipeline5.10/bin/unsquashfs: error while loading shared libraries: libz.so.1: cannot open shared object file: No such file or directory`

Which seems like it could be due to an [issue with singularity](https://github.com/sylabs/singularity/issues/273)?

This run was performed in a new conda environment with snakemake 5.10.0 and singularity 3.8.7, although I get the same zlib issue when using different versions of both packages (including snakemake 5.10.0 and singularity 2.5.2 as suggestion in the README). 

Do you have any recommendations for which combinations of snakemake and singularity versions might work?

**Comment by weber8thomas** [comment]
Thank you for looking for where the error could have come from.

Looks like singularity don't succeed to find your `libz.so.1` compression library file. 

What's your OS ? (please provide the output of `cat /etc/os-release`) 

Once the `libz.so.1` file location identified (according OS), you may test again by defining something like this : `export LD_RUN_PATH="$LIBZ.SO.1 LOCATION"` before running snakemake command.

> Do you have any recommendations for which combinations of snakemake and singularity versions might work?

I'm not super familiar with snakemake x singularity at the moment but is working on an update of mosaicatcher (based on conda only in a first step) that will solve most of the main issues of the pipeline.

**Comment by benedict909** [comment]
Hi Thomas, 

here is the output:

```
> cat /etc/os-release
NAME="Rocky Linux"
VERSION="8.5 (Green Obsidian)"
ID="rocky"
ID_LIKE="rhel centos fedora"
VERSION_ID="8.5"
PLATFORM_ID="platform:el8"
PRETTY_NAME="Rocky Linux 8.5 (Green Obsidian)"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:rocky:rocky:8:GA"
HOME_URL="https://rockylinux.org/"
BUG_REPORT_URL="https://bugs.rockylinux.org/"
ROCKY_SUPPORT_PRODUCT="Rocky Linux"
ROCKY_SUPPORT_PRODUCT_VERSION="8"
```

libz.so.1 is in my conda environment here: `/fast/users/bmontei_m/work/miniconda/envs/pipeline5.10/lib/libz.so.1`, in my conda lib here: `/data/gpfs-1/users/bmontei_m/work/miniconda/lib/libz.so.1` (the `-L` flag of `$LDFLAGS_USED`) and in my root system here: `/lib64/libz.so.1`. 

And a conda release sounds great! 
Thanks again for your help with this 🙂

**Comment by weber8thomas** [comment]
Hi Benedict, 

Sorry for the delay and thanks for the answer ! 

I'm not sure it will work but could you try to set the LD_RUN_PATH as the following `export LD_RUN_PATH=/lib64` and run again the execution ?
