### ISSUE TITLE
samtools version change

### ISSUE THREAD

**Issue by maryamghr** [friendsofstrandseq/mosaicatcher-pipeline#3]
samtools 1.10 has a bug in merging. It should be downgraded in the conda environment.

**Comment by tobiasmarschall** [comment]
There seem to be different flavors of 1.10: 1.10-3,  1.10-2,  1.10-1,  1.10-0... 
Does the bug apply to all of these? What exactly is that bug? Has it been reported to the samtools/htslib folks?

**Comment by daewoooo** [comment]
You can eventually use sambamba tools to do merging. Should even faster
than samtools.
